const types = {
  UPDATE_LOGIN_CK: 'UPDATE_LOGIN_CK',
  UPDATE_FCM_TOKEN: 'UPDATE_FCM_TOKEN',
  UPDATE_INDEX: 'UPDATE_INDEX',
  UPDATE_GPS: 'UPDATE_GPS',
  UPDATE_SITE: 'UPDATE_SITE',
  UPDATE_STORE: 'UPDATE_STORE',
  SELECT_STORE: 'SELECT_STORE',
  UPDATE_COUPON_LIST: 'UPDATE_COUPON_LIST',
  UPDATE_REGULAR_HOLIDAY: 'UPDATE_REGULAR_HOLIDAY',
  UPDATE_STORE_TIME: 'UPDATE_STORE_TIME',
  UPDATE_CLOSED_LIST: 'UPDATE_CLOSED_LIST',
  SELECT_ORDER_TAB: 'SELECT_ORDER_TAB',
  GET_NEW_ORDER_LIST: 'GET_NEW_ORDER_LIST',
  UPDATE_NEW_ORDER_LIST: 'UPDATE_NEW_ORDER_LIST',
  GET_CHECK_ORDER_LIST: 'GET_CHECK_ORDER_LIST',
  UPDATE_CHECK_ORDER_LIST: 'UPDATE_CHECK_ORDER_LIST',
  GET_DELIVERY_ORDER_LIST: 'GET_DELIVERY_ORDER_LIST',
  UPDATE_DELIVERY_ORDER_LIST: 'UPDATE_DELIVERY_ORDER_LIST',
  GET_DONE_ORDER_LIST: 'GET_DONE_ORDER_LIST',
  UPDATE_DONE_ORDER_LIST: 'UPDATE_DONE_ORDER_LIST',
  GET_USERS_REQUESTED: 'GET_USERS_REQUESTED',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILED: 'GET_USERS_FAILED',
  GET_NEWS: 'GET_NEWS',
  NEWS_RECEIVED: 'NEWS_RECEIVED'
}

export default types
